# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: false
os:
  - linux
  - osx
osx_image: xcode9.2
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))' ; fi
  skip_cleanup: true
